on:
  push:
    branches: [main]
    paths:
      - "infra/environments/dev/**"
      - "infra/modules/**"
jobs:
  terraform-deploy-dev:
    defaults:
      run:
        working-directory: ./infra/environments/dev
    runs-on: ubuntu-latest
    environment:
      name: dev

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          # only include the necessary files
          sparse-checkout: |
            infra/environments/dev
            infra/modules
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "1.14.7"
      - name: Terraform Init
        run: terraform init
      - name: Terraform Apply
        run: terraform apply -auto-approve
