on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "ui/**"

permissions:
  # AWS OIDC
  id-token: write
  # Bring back read permissions since defaults are overwritten
  contents: read

jobs:
  ui-deploy-dev:
    defaults:
      run:
        working-directory: ./ui
    runs-on: ubuntu-latest
    environment:
      name: dev

    steps:
      - name: Checkout the code
        uses: actions/checkout@v6
        with:
          # only include the necessary files
          sparse-checkout: |
            ui

      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          version: ^10.32.1

      - name: Install correct node version
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "pnpm"
          cache-dependency-path: ui/pnpm-lock.yaml

      - name: Create .env file
        # load into env variable then make to file to prevent bash from stripping out newlines needed by terraform
        env:
          NEXT_ENV_VARS: ${{ vars.NEXT_ENV_VARS }}
        run: echo "$NEXT_ENV_VARS" > .env

      - name: Install pnpm dependencies
        run: pnpm install

      - name: Build static files
        run: pnpm build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Deploy to S3
        # syncs build files with s3 bucket
        # --delete needed to remove files not in updated build
        run: aws s3 sync ./out s3://${{ vars.S3_BUCKET_NAME }} --delete

      - name: Invalidate CloudFront cache
        run: aws cloudfront create-invalidation --distribution-id ${{ vars.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
