on:
  pull_request:
    branches: [main]
    paths:
      - "infra/environments/dev/**"
      - "infra/modules/**"

permissions:
  # AWS OIDC
  id-token: write
  pull-requests: write
  # needed since we are now defining permissions
  contents: read

jobs:
  terraform-plan-dev:
    defaults:
      run:
        working-directory: ./infra/environments/dev
    runs-on: ubuntu-latest
    environment:
      name: dev

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          # only include the necessary files
          sparse-checkout: |
            infra/environments/dev
            infra/modules
            .github/scripts

      - name: AWS Auth
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Create tfvars file
        run: echo "${{ secrets.TFVARS }}" > terraform.tfvars

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "1.14.7"
      - name: Terraform Init
        run: terraform init
      - name: Terraform Plan
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        id: tf-plan
        run: terraform plan -no-color
        continue-on-error: true
      - name: Comment on PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PLAN_STATUS: ${{ steps.tf-plan.outcome }}
        run: bash $GITHUB_WORKSPACE/.github/scripts/pr-plan-comment.sh
      - name: Fail job
        if: steps.tf-plan.outcome == 'failure'
        run: exit 1
